// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/user/user.proto

package pbuser

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mozyy/empty-news/proto/pbmodel"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
