// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v2.0.0
// 	protoc        (unknown)
// source: user/login/v1/login.proto

package loginv1

import (
	context "context"
	v1 "github.com/mozyy/empty-news/proto/system/role/v1"
	_ "github.com/mozyy/empty-news/proto/user/oauth/v1"
	_ "github.com/mozyy/protoc-gen-gorm/options"
	types "github.com/mozyy/protoc-gen-gorm/types"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	time "time"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoResponseGORM struct {
	ID uint32 `gorm:"primaryKey"`
	// 用户名
	Name string
	// 手机号
	Mobile string
	// 角色
	ResourceItems []*v1.RoleGORM
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
	DeletedAt     *types.DeletedAt `gorm:"index"`
}

// TableName overrides the default tablename generated by GORM
func (InfoResponseGORM) TableName() string {
	return "user_info_responses"
}

// ToPB  converts the fields of this object to PB object
func (m *InfoResponseGORM) ToPB(ctx context.Context) *InfoResponse {
	to := InfoResponse{}
	to.ID = m.ID
	to.Name = m.Name
	to.Mobile = m.Mobile
	for _, ResourceItems := range m.ResourceItems {
		to.ResourceItems = append(to.ResourceItems, ResourceItems.ToPB(ctx))
	}
	if m.CreatedAt != nil {
		to.CreatedAt = timestamppb.New(*m.CreatedAt)
	}
	if m.UpdatedAt != nil {
		to.UpdatedAt = timestamppb.New(*m.UpdatedAt)
	}
	to.DeletedAt = m.DeletedAt
	return &to
}

// ToORM  converts the fields of this object to PB object
func (m *InfoResponse) ToORM(ctx context.Context) *InfoResponseGORM {
	to := InfoResponseGORM{}
	to.ID = m.GetID()
	to.Name = m.GetName()
	to.Mobile = m.GetMobile()
	for _, ResourceItems := range m.GetResourceItems() {
		to.ResourceItems = append(to.ResourceItems, ResourceItems.ToORM(ctx))
	}
	if m.GetCreatedAt() != nil {
		CreatedAt := m.GetCreatedAt().AsTime()
		to.CreatedAt = &CreatedAt
	}
	if m.GetUpdatedAt() != nil {
		UpdatedAt := m.GetUpdatedAt().AsTime()
		to.UpdatedAt = &UpdatedAt
	}
	to.DeletedAt = m.GetDeletedAt()
	return &to
}
