// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/model/conf.proto

package pbmodel

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mozyy/empty-news/utils/orm"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	gorm_io_gorm "gorm.io/gorm"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ConfORM struct {
	ID        uint32 `gorm:"primary_key"`
	Type      string
	Value     string
	Content   string
	Desc      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm_io_gorm.DeletedAt `gorm:"index"`
}

func (*ConfORM) TableName() string {
	return "confs"
}

func (o *ConfORM) ToPB() *Conf {
	value := &Conf{
		ID:        o.ID,
		Type:      o.Type,
		Value:     o.Value,
		Content:   o.Content,
		Desc:      o.Desc,
		CreatedAt: timestamppb.New(o.CreatedAt),
		UpdatedAt: timestamppb.New(o.UpdatedAt),
	}
	deletedAtValue, _ := o.DeletedAt.Value()
	if deletedAt, ok := deletedAtValue.(time.Time); ok {
		value.DeletedAt = timestamppb.New(deletedAt)
	}
	return value
}

func (s *Conf) ToORM() *ConfORM {
	value := &ConfORM{
		ID:        s.ID,
		Type:      s.Type,
		Value:     s.Value,
		Content:   s.Content,
		Desc:      s.Desc,
		CreatedAt: s.CreatedAt.AsTime(),
		UpdatedAt: s.UpdatedAt.AsTime(),
	}
	value.DeletedAt.Scan(s.DeletedAt)
	return value
}

type ConfApiORM struct {
	ID        uint32 `gorm:"primary_key"`
	Api       string
	Scope     string
	Desc      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm_io_gorm.DeletedAt `gorm:"index"`
}

func (*ConfApiORM) TableName() string {
	return "conf_apis"
}

func (o *ConfApiORM) ToPB() *ConfApi {
	value := &ConfApi{
		ID:        o.ID,
		Api:       o.Api,
		Scope:     o.Scope,
		Desc:      o.Desc,
		CreatedAt: timestamppb.New(o.CreatedAt),
		UpdatedAt: timestamppb.New(o.UpdatedAt),
	}
	deletedAtValue, _ := o.DeletedAt.Value()
	if deletedAt, ok := deletedAtValue.(time.Time); ok {
		value.DeletedAt = timestamppb.New(deletedAt)
	}
	return value
}

func (s *ConfApi) ToORM() *ConfApiORM {
	value := &ConfApiORM{
		ID:        s.ID,
		Api:       s.Api,
		Scope:     s.Scope,
		Desc:      s.Desc,
		CreatedAt: s.CreatedAt.AsTime(),
		UpdatedAt: s.UpdatedAt.AsTime(),
	}
	value.DeletedAt.Scan(s.DeletedAt)
	return value
}
