// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v2.0.0
// 	protoc        v3.20.0
// source: proto/model/conf.proto

package pbmodel

import (
	context "context"
	_ "github.com/mozyy/protoc-gen-gorm/options"
	types "github.com/mozyy/protoc-gen-gorm/types"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	time "time"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfGORM struct {
	ID        uint32 `gorm:"primaryKey"`
	Type      string
	Value     string
	Content   string
	Desc      string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *types.DeletedAt `gorm:"index"`
}

// TableName overrides the default tablename generated by GORM
func (ConfGORM) TableName() string {
	return "confs"
}

// ToPB  converts the fields of this object to PB object
func (m *ConfGORM) ToPB(ctx context.Context) *Conf {
	to := Conf{}
	to.ID = m.ID
	to.Type = m.Type
	to.Value = m.Value
	to.Content = m.Content
	to.Desc = m.Desc
	if m.CreatedAt != nil {
		to.CreatedAt = timestamppb.New(*m.CreatedAt)
	}
	if m.UpdatedAt != nil {
		to.UpdatedAt = timestamppb.New(*m.UpdatedAt)
	}
	to.DeletedAt = m.DeletedAt
	return &to
}

// ToORM  converts the fields of this object to PB object
func (m *Conf) ToORM(ctx context.Context) *ConfGORM {
	to := ConfGORM{}
	to.ID = m.GetID()
	to.Type = m.GetType()
	to.Value = m.GetValue()
	to.Content = m.GetContent()
	to.Desc = m.GetDesc()
	if m.GetCreatedAt() != nil {
		CreatedAt := m.GetCreatedAt().AsTime()
		to.CreatedAt = &CreatedAt
	}
	if m.GetUpdatedAt() != nil {
		UpdatedAt := m.GetUpdatedAt().AsTime()
		to.UpdatedAt = &UpdatedAt
	}
	to.DeletedAt = m.GetDeletedAt()
	return &to
}

type ConfApiGORM struct {
	ID        uint32 `gorm:"primaryKey"`
	Api       string
	Scope     string
	Desc      string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *types.DeletedAt `gorm:"index"`
}

// TableName overrides the default tablename generated by GORM
func (ConfApiGORM) TableName() string {
	return "conf_apis"
}

// ToPB  converts the fields of this object to PB object
func (m *ConfApiGORM) ToPB(ctx context.Context) *ConfApi {
	to := ConfApi{}
	to.ID = m.ID
	to.Api = m.Api
	to.Scope = m.Scope
	to.Desc = m.Desc
	if m.CreatedAt != nil {
		to.CreatedAt = timestamppb.New(*m.CreatedAt)
	}
	if m.UpdatedAt != nil {
		to.UpdatedAt = timestamppb.New(*m.UpdatedAt)
	}
	to.DeletedAt = m.DeletedAt
	return &to
}

// ToORM  converts the fields of this object to PB object
func (m *ConfApi) ToORM(ctx context.Context) *ConfApiGORM {
	to := ConfApiGORM{}
	to.ID = m.GetID()
	to.Api = m.GetApi()
	to.Scope = m.GetScope()
	to.Desc = m.GetDesc()
	if m.GetCreatedAt() != nil {
		CreatedAt := m.GetCreatedAt().AsTime()
		to.CreatedAt = &CreatedAt
	}
	if m.GetUpdatedAt() != nil {
		UpdatedAt := m.GetUpdatedAt().AsTime()
		to.UpdatedAt = &UpdatedAt
	}
	to.DeletedAt = m.GetDeletedAt()
	return &to
}
