// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/model/user.proto

package pbmodel

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mozyy/empty-news/utils/orm"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	gorm_io_gorm "gorm.io/gorm"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserORM struct {
	ID           uint32 `gorm:"primary_key"`
	Mobile       string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    gorm_io_gorm.DeletedAt `gorm:"index"`
}

func (*UserORM) TableName() string {
	return "users"
}

func (o *UserORM) ToPB() *User {
	value := &User{
		ID:           o.ID,
		Mobile:       o.Mobile,
		PasswordHash: o.PasswordHash,
		CreatedAt:    timestamppb.New(o.CreatedAt),
		UpdatedAt:    timestamppb.New(o.UpdatedAt),
	}
	deletedAtValue, _ := o.DeletedAt.Value()
	if deletedAt, ok := deletedAtValue.(time.Time); ok {
		value.DeletedAt = timestamppb.New(deletedAt)
	}
	return value
}

func (s *User) ToORM() *UserORM {
	value := &UserORM{
		ID:           s.ID,
		Mobile:       s.Mobile,
		PasswordHash: s.PasswordHash,
		CreatedAt:    s.CreatedAt.AsTime(),
		UpdatedAt:    s.UpdatedAt.AsTime(),
	}
	value.DeletedAt.Scan(s.DeletedAt)
	return value
}
