// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v2.0.0
// 	protoc        (unknown)
// source: system/role/v1/role.proto

package rolev1

import (
	context "context"
	v1 "github.com/mozyy/empty-news/proto/system/resource/v1"
	_ "github.com/mozyy/protoc-gen-gorm/options"
	types "github.com/mozyy/protoc-gen-gorm/types"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	time "time"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleGORM struct {
	ID uint32 `gorm:"primaryKey"`
	// 角色名
	Name string `gorm:"unique"`
	// 资源
	ResourceItems []*v1.ResourceGORM
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
	DeletedAt     *types.DeletedAt `gorm:"index"`
}

// TableName overrides the default tablename generated by GORM
func (RoleGORM) TableName() string {
	return "role_roles"
}

// ToPB  converts the fields of this object to PB object
func (m *RoleGORM) ToPB(ctx context.Context) *Role {
	to := Role{}
	to.ID = m.ID
	to.Name = m.Name
	for _, ResourceItems := range m.ResourceItems {
		to.ResourceItems = append(to.ResourceItems, ResourceItems.ToPB(ctx))
	}
	if m.CreatedAt != nil {
		to.CreatedAt = timestamppb.New(*m.CreatedAt)
	}
	if m.UpdatedAt != nil {
		to.UpdatedAt = timestamppb.New(*m.UpdatedAt)
	}
	to.DeletedAt = m.DeletedAt
	return &to
}

// ToORM  converts the fields of this object to PB object
func (m *Role) ToORM(ctx context.Context) *RoleGORM {
	to := RoleGORM{}
	to.ID = m.GetID()
	to.Name = m.GetName()
	for _, ResourceItems := range m.GetResourceItems() {
		to.ResourceItems = append(to.ResourceItems, ResourceItems.ToORM(ctx))
	}
	if m.GetCreatedAt() != nil {
		CreatedAt := m.GetCreatedAt().AsTime()
		to.CreatedAt = &CreatedAt
	}
	if m.GetUpdatedAt() != nil {
		UpdatedAt := m.GetUpdatedAt().AsTime()
		to.UpdatedAt = &UpdatedAt
	}
	to.DeletedAt = m.GetDeletedAt()
	return &to
}
