// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v2.0.0
// 	protoc        v3.20.0
// source: proto/manage/role.proto

package pbmanage

import (
	context "context"
	_ "github.com/mozyy/protoc-gen-gorm/options"
	types "github.com/mozyy/protoc-gen-gorm/types"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	time "time"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleItemGORM struct {
	ID            uint32 `gorm:"primaryKey"`
	Name          string `gorm:"unique"`
	ResourceItems []*ResourceItemGORM
	Active        bool
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
	DeletedAt     *types.DeletedAt `gorm:"index"`
}

// TableName overrides the default tablename generated by GORM
func (RoleItemGORM) TableName() string {
	return "role_items"
}

// ToPB  converts the fields of this object to PB object
func (m *RoleItemGORM) ToPB(ctx context.Context) *RoleItem {
	to := RoleItem{}
	to.ID = m.ID
	to.Name = m.Name
	for _, ResourceItems := range m.ResourceItems {
		to.ResourceItems = append(to.ResourceItems, ResourceItems.ToPB(ctx))
	}
	to.Active = m.Active
	if m.CreatedAt != nil {
		to.CreatedAt = timestamppb.New(*m.CreatedAt)
	}
	if m.UpdatedAt != nil {
		to.UpdatedAt = timestamppb.New(*m.UpdatedAt)
	}
	to.DeletedAt = m.DeletedAt
	return &to
}

// ToORM  converts the fields of this object to PB object
func (m *RoleItem) ToORM(ctx context.Context) *RoleItemGORM {
	to := RoleItemGORM{}
	to.ID = m.GetID()
	to.Name = m.GetName()
	for _, ResourceItems := range m.GetResourceItems() {
		to.ResourceItems = append(to.ResourceItems, ResourceItems.ToORM(ctx))
	}
	to.Active = m.GetActive()
	if m.GetCreatedAt() != nil {
		CreatedAt := m.GetCreatedAt().AsTime()
		to.CreatedAt = &CreatedAt
	}
	if m.GetUpdatedAt() != nil {
		UpdatedAt := m.GetUpdatedAt().AsTime()
		to.UpdatedAt = &UpdatedAt
	}
	to.DeletedAt = m.GetDeletedAt()
	return &to
}
