// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: proto/manage/sources.proto

package pbmanage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SourcesClient is the client API for Sources service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SourcesClient interface {
	Create(ctx context.Context, in *SourcesItem, opts ...grpc.CallOption) (*SourcesItem, error)
	Update(ctx context.Context, in *SourcesItem, opts ...grpc.CallOption) (*SourcesItem, error)
	List(ctx context.Context, in *SourcesItem, opts ...grpc.CallOption) (*ListResponse, error)
	Delete(ctx context.Context, in *SourcesItem, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sourcesClient struct {
	cc grpc.ClientConnInterface
}

func NewSourcesClient(cc grpc.ClientConnInterface) SourcesClient {
	return &sourcesClient{cc}
}

func (c *sourcesClient) Create(ctx context.Context, in *SourcesItem, opts ...grpc.CallOption) (*SourcesItem, error) {
	out := new(SourcesItem)
	err := c.cc.Invoke(ctx, "/manage.Sources/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourcesClient) Update(ctx context.Context, in *SourcesItem, opts ...grpc.CallOption) (*SourcesItem, error) {
	out := new(SourcesItem)
	err := c.cc.Invoke(ctx, "/manage.Sources/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourcesClient) List(ctx context.Context, in *SourcesItem, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/manage.Sources/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourcesClient) Delete(ctx context.Context, in *SourcesItem, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/manage.Sources/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourcesServer is the server API for Sources service.
// All implementations must embed UnimplementedSourcesServer
// for forward compatibility
type SourcesServer interface {
	Create(context.Context, *SourcesItem) (*SourcesItem, error)
	Update(context.Context, *SourcesItem) (*SourcesItem, error)
	List(context.Context, *SourcesItem) (*ListResponse, error)
	Delete(context.Context, *SourcesItem) (*emptypb.Empty, error)
	mustEmbedUnimplementedSourcesServer()
}

// UnimplementedSourcesServer must be embedded to have forward compatible implementations.
type UnimplementedSourcesServer struct {
}

func (UnimplementedSourcesServer) Create(context.Context, *SourcesItem) (*SourcesItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSourcesServer) Update(context.Context, *SourcesItem) (*SourcesItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSourcesServer) List(context.Context, *SourcesItem) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSourcesServer) Delete(context.Context, *SourcesItem) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSourcesServer) mustEmbedUnimplementedSourcesServer() {}

// UnsafeSourcesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourcesServer will
// result in compilation errors.
type UnsafeSourcesServer interface {
	mustEmbedUnimplementedSourcesServer()
}

func RegisterSourcesServer(s grpc.ServiceRegistrar, srv SourcesServer) {
	s.RegisterService(&Sources_ServiceDesc, srv)
}

func _Sources_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourcesItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourcesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manage.Sources/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourcesServer).Create(ctx, req.(*SourcesItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sources_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourcesItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourcesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manage.Sources/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourcesServer).Update(ctx, req.(*SourcesItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sources_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourcesItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourcesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manage.Sources/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourcesServer).List(ctx, req.(*SourcesItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sources_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourcesItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourcesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manage.Sources/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourcesServer).Delete(ctx, req.(*SourcesItem))
	}
	return interceptor(ctx, in, info, handler)
}

// Sources_ServiceDesc is the grpc.ServiceDesc for Sources service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sources_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manage.Sources",
	HandlerType: (*SourcesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Sources_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Sources_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Sources_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Sources_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/manage/sources.proto",
}
