// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v2.0.0
// 	protoc        (unknown)
// source: user/oauth/v1/oauth.proto

package oauthv1

import (
	context "context"
	_ "github.com/mozyy/protoc-gen-gorm/options"
	types "github.com/mozyy/protoc-gen-gorm/types"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	time "time"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenInfo implement oauth2.TokenInfo
type TokenInfoGORM struct {
	ID uint32 `gorm:"primaryKey"`
	// 客户端id
	ClientID string
	// 用户id
	UserID string
	// 回调地址
	RedirectURI string
	// 请求权限
	Scope string
	// code
	Code string
	// code 创建时间
	CodeCreateAt        *time.Time
	CodeExpiresIn       int64
	CodeChallenge       string
	CodeChallengeMethod CodeChallengeMethod
	// access
	Access          string
	AccessCreateAt  *time.Time
	AccessExpiresIn int64
	// 刷新
	Refresh          string
	RefreshCreateAt  *time.Time
	RefreshExpiresIn int64
	TokenType        string
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	DeletedAt        *types.DeletedAt `gorm:"index"`
}

// TableName overrides the default tablename generated by GORM
func (TokenInfoGORM) TableName() string {
	return "token_infos"
}

// ToPB  converts the fields of this object to PB object
func (m *TokenInfoGORM) ToPB(ctx context.Context) *TokenInfo {
	to := TokenInfo{}
	to.ID = m.ID
	to.ClientID = m.ClientID
	to.UserID = m.UserID
	to.RedirectURI = m.RedirectURI
	to.Scope = m.Scope
	to.Code = m.Code
	if m.CodeCreateAt != nil {
		to.CodeCreateAt = timestamppb.New(*m.CodeCreateAt)
	}
	to.CodeExpiresIn = m.CodeExpiresIn
	to.CodeChallenge = m.CodeChallenge
	to.CodeChallengeMethod = m.CodeChallengeMethod
	to.Access = m.Access
	if m.AccessCreateAt != nil {
		to.AccessCreateAt = timestamppb.New(*m.AccessCreateAt)
	}
	to.AccessExpiresIn = m.AccessExpiresIn
	to.Refresh = m.Refresh
	if m.RefreshCreateAt != nil {
		to.RefreshCreateAt = timestamppb.New(*m.RefreshCreateAt)
	}
	to.RefreshExpiresIn = m.RefreshExpiresIn
	to.TokenType = m.TokenType
	if m.CreatedAt != nil {
		to.CreatedAt = timestamppb.New(*m.CreatedAt)
	}
	if m.UpdatedAt != nil {
		to.UpdatedAt = timestamppb.New(*m.UpdatedAt)
	}
	to.DeletedAt = m.DeletedAt
	return &to
}

// ToORM  converts the fields of this object to PB object
func (m *TokenInfo) ToORM(ctx context.Context) *TokenInfoGORM {
	to := TokenInfoGORM{}
	to.ID = m.GetID()
	to.ClientID = m.GetClientID()
	to.UserID = m.GetUserID()
	to.RedirectURI = m.GetRedirectURI()
	to.Scope = m.GetScope()
	to.Code = m.GetCode()
	if m.GetCodeCreateAt() != nil {
		CodeCreateAt := m.GetCodeCreateAt().AsTime()
		to.CodeCreateAt = &CodeCreateAt
	}
	to.CodeExpiresIn = m.GetCodeExpiresIn()
	to.CodeChallenge = m.GetCodeChallenge()
	to.CodeChallengeMethod = m.GetCodeChallengeMethod()
	to.Access = m.GetAccess()
	if m.GetAccessCreateAt() != nil {
		AccessCreateAt := m.GetAccessCreateAt().AsTime()
		to.AccessCreateAt = &AccessCreateAt
	}
	to.AccessExpiresIn = m.GetAccessExpiresIn()
	to.Refresh = m.GetRefresh()
	if m.GetRefreshCreateAt() != nil {
		RefreshCreateAt := m.GetRefreshCreateAt().AsTime()
		to.RefreshCreateAt = &RefreshCreateAt
	}
	to.RefreshExpiresIn = m.GetRefreshExpiresIn()
	to.TokenType = m.GetTokenType()
	if m.GetCreatedAt() != nil {
		CreatedAt := m.GetCreatedAt().AsTime()
		to.CreatedAt = &CreatedAt
	}
	if m.GetUpdatedAt() != nil {
		UpdatedAt := m.GetUpdatedAt().AsTime()
		to.UpdatedAt = &UpdatedAt
	}
	to.DeletedAt = m.GetDeletedAt()
	return &to
}

// ClientStore implement oauth2.ClientStore
type ClientStoreGORM struct {
	ID        uint32 `gorm:"primaryKey"`
	Secret    string
	Domain    string
	UserID    string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *types.DeletedAt `gorm:"index"`
}

// TableName overrides the default tablename generated by GORM
func (ClientStoreGORM) TableName() string {
	return "client_stores"
}

// ToPB  converts the fields of this object to PB object
func (m *ClientStoreGORM) ToPB(ctx context.Context) *ClientStore {
	to := ClientStore{}
	to.ID = m.ID
	to.Secret = m.Secret
	to.Domain = m.Domain
	to.UserID = m.UserID
	if m.CreatedAt != nil {
		to.CreatedAt = timestamppb.New(*m.CreatedAt)
	}
	if m.UpdatedAt != nil {
		to.UpdatedAt = timestamppb.New(*m.UpdatedAt)
	}
	to.DeletedAt = m.DeletedAt
	return &to
}

// ToORM  converts the fields of this object to PB object
func (m *ClientStore) ToORM(ctx context.Context) *ClientStoreGORM {
	to := ClientStoreGORM{}
	to.ID = m.GetID()
	to.Secret = m.GetSecret()
	to.Domain = m.GetDomain()
	to.UserID = m.GetUserID()
	if m.GetCreatedAt() != nil {
		CreatedAt := m.GetCreatedAt().AsTime()
		to.CreatedAt = &CreatedAt
	}
	if m.GetUpdatedAt() != nil {
		UpdatedAt := m.GetUpdatedAt().AsTime()
		to.UpdatedAt = &UpdatedAt
	}
	to.DeletedAt = m.GetDeletedAt()
	return &to
}
